/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Entidades.*;
import ReporteLote.Reporte;
import Helpers.ButtonEditor;
import Helpers.ButtonRenderer;
import java.beans.PropertyVetoException;
import java.util.List;
import java.util.ListIterator;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MUTNPROD003
 */
public class Ventana_1 extends javax.swing.JFrame {

    private int sizeRamdom;
    private DefaultTableModel model;
    private TrazaDao traza;
    private ListIterator iterator;
    private boolean hasNext;
    private boolean hasPrevius;
    private int contador = 1;
    private boolean guardado;
    private int zoom;
    private ImagenesWorker worker;
    private boolean pdf;

    public Ventana_1(TrazaDao traza) {
        initComponents();
        String rutaImagen = "Logos/nuevo logo sin letras UTN.png";
        ImageIcon im = new ImageIcon(rutaImagen);
        setIconImage(im.getImage());
//        tablaCheck.requestFocus();
        setExtendedState(6);
        this.traza = traza;
        poblarTabla();
        guardado = true;
        terminar.setEnabled(false);
        this.pdf = (traza.getExtension().equals(".pdf")) ? true : false;
        internal(pdf);

    }

    private void internal(boolean ispdf) {
        try {
            internal.setMaximum(true);
            Imagen siguientes = nextImagen();//trae el ramdom
            anterior.setEnabled(false);
            String rutaDb = siguientes.getRutaDb();//ruta de archivo
            internal.setTitle("Imagen " + contador + "/" + getSizeRamdom());
            rutaJlabel.setText(rutaDb);
            internal.setVisible(true);
            String verImagen = filtroImagen(ispdf, siguientes);
            VisualizarImagen visualizarImagen = new VisualizarImagen(verImagen, scrollimage, slider, getZoom());
            int id = siguientes.getId();
            new SetChecksBox(tablaCheck).setEstadoChecksBoxs(id);
            contador++;
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Ventana_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ListIterator getIterator() {
        return iterator;
    }

    private Imagen nextImagen() {
        Imagen tif = null;
        try {
            ListIterator it = getIterator();
            tif = (Imagen) it.next();
            hasNext = (!it.hasNext()) ? false : true;
        } catch (NoSuchElementException e) {
            System.out.println(e.getMessage());
        }
        return tif;
    }

    private Imagen previus() {
        Imagen tif = null;
        try {
            ListIterator it = getIterator();
            tif = (Imagen) it.previous();
            hasPrevius = (!it.hasPrevious()) ? false : true;
        } catch (NoSuchElementException e) {
            System.out.println(e.getMessage());
        }
        return tif;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        siguiente = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        terminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        internal = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        scrollimage = new javax.swing.JScrollPane();
        slider = new javax.swing.JSlider();
        rutaJlabel = new javax.swing.JLabel();
        pagina = new javax.swing.JLabel();
        panelButtCheck = new javax.swing.JPanel();
        scrollChecks = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCheck = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 252, 238));

        jPanel1.setBackground(new java.awt.Color(230, 252, 238));

        siguiente.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        anterior.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        terminar.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        terminar.setText("Terminar");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });

        internal.setBackground(new java.awt.Color(230, 252, 238));
        internal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        internal.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        internal.setIconifiable(true);
        internal.setMaximizable(true);
        internal.setResizable(true);
        internal.setTitle("Qualitys_control de imágenes");
        internal.setNextFocusableComponent(tablaCheck);
        internal.setVisible(true);

        slider.setMajorTickSpacing(10);
        slider.setPaintTicks(true);
        slider.setValue(25);

        rutaJlabel.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        rutaJlabel.setText("RUTA");

        pagina.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        pagina.setText("Pagina: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rutaJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pagina, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(scrollimage)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutaJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollimage))
        );

        scrollChecks.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jScrollPane4.setBorder(null);

        tablaCheck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Nombre", "?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaCheck.setNextFocusableComponent(siguiente);
        jScrollPane4.setViewportView(tablaCheck);

        scrollChecks.setViewportView(jScrollPane4);

        javax.swing.GroupLayout panelButtCheckLayout = new javax.swing.GroupLayout(panelButtCheck);
        panelButtCheck.setLayout(panelButtCheckLayout);
        panelButtCheckLayout.setHorizontalGroup(
            panelButtCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtCheckLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(scrollChecks, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelButtCheckLayout.setVerticalGroup(
            panelButtCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollChecks, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout internalLayout = new javax.swing.GroupLayout(internal.getContentPane());
        internal.getContentPane().setLayout(internalLayout);
        internalLayout.setHorizontalGroup(
            internalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelButtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        internalLayout.setVerticalGroup(
            internalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalLayout.createSequentialGroup()
                .addGroup(internalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelButtCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        internal.setBounds(10, 10, 810, 480);
        jDesktopPane1.add(internal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setViewportView(jDesktopPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(67, 67, 67)
                .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed
        ActionGuardar();
    }//GEN-LAST:event_terminarActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        siguienteSuceso();
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        AnteriorSuceso();
    }//GEN-LAST:event_anteriorActionPerformed

    private void poblarTabla() {
        model = (DefaultTableModel) tablaCheck.getModel();
        tablaCheck.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tablaCheck.getColumnModel().getColumn(0).setPreferredWidth(20);
        tablaCheck.getColumnModel().getColumn(1).setPreferredWidth(230);
        tablaCheck.getColumnModel().getColumn(2).setPreferredWidth(20);
        iterator = traza.getListaTif().listIterator();
        List<TiposConCheck> lt = traza.getListaTipos();
        for (TiposConCheck tipos : lt) {
            boolean ischeck = tipos.isCheck();
            String nombre = tipos.getNombre();
            String boton = "Boton";
            Object[] object = new Object[]{ischeck, nombre, tipos.getId()};
            tablaCheck.getColumn("?").setCellRenderer(new ButtonRenderer());
            tablaCheck.getColumn("?").setCellEditor(
                    new ButtonEditor(new JCheckBox(), lt));
            model.addRow(object);
        }
    }

    private void ActionGuardar() {
        Guardar save = new Guardar(traza, rutaJlabel.getText().toString(), tablaCheck);
        final int id = traza.getId();
        NumeroDeArchivosRechazados numeroRechazo = new NumeroDeArchivosRechazados(id);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Reporte(id).setVisible(true);
            }
        });
        dispose();
    }
    private void siguienteSuceso() {
        String ruta_temp;
        try {
            Guardar guardar = new Guardar(traza, rutaJlabel.getText().toString(), tablaCheck);
            int setSize = getSizeRamdom() + 1;
            setSizeRamdom(setSize);
            setZoom(slider.getValue());
            Next proximo = new Next(anterior, siguiente, getSizeRamdom(), internal, rutaJlabel, pagina, tablaCheck);
            Imagen isNext = nextImagen();
            proximo.crearInternalFrame(contador++, isNext, isHasNext());
            setZoom(slider.getValue());
            VisualizarImagen visualizarImagen = new VisualizarImagen(filtroImagen(pdf, isNext), scrollimage, slider, getZoom());
            if (!isHasNext()) {
                siguiente.setEnabled(false);
                terminar.setEnabled(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(Ventana_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void AnteriorSuceso() {

        Guardar save = new Guardar(traza, rutaJlabel.getText().toString(), tablaCheck);
        int descontar = 1;
        int der = contador - descontar;
        setContador(der);
        Imagen imagenAnterior = previus();
        Previus previus = new Previus(siguiente, internal, rutaJlabel, pagina, getSizeRamdom(), tablaCheck);
        previus.setearInternalFrame(getContador(), imagenAnterior);
        VisualizarImagen visualizarImagen = new VisualizarImagen(imagenAnterior.getRutaTemp(), scrollimage, slider, getZoom());
        if (!hasPrevius) {
            anterior.setEnabled(false);
        }
//        String visualizacion = "";
//        Guardar save = new Guardar(traza, rutaJlabel.getText().toString(), tablaCheck);
//        int descontar = 1;
//        int der = contador - descontar;
//        setContador(der);
//        visualizacion = new Botones(tablaCheck, rutaJlabel, pagina, siguiente,
//                internal, getSizeRamdom(), pdf, previus(), getContador()).Anterior();
//        VisualizarImagen visualizarImagen = new VisualizarImagen(visualizacion, scrollimage, slider, getZoom());
//        if (!hasPrevius) {
//            anterior.setEnabled(false);
//        }
    }

    public int getZoom() {
        return slider.getValue();
    }

    public void setZoom(int zoom) {
        this.zoom = zoom;
    }

    public boolean isHasNext() {
        return hasNext;
    }

    public void setContador(int contador) {
        this.contador = contador;
    }

    public boolean isGuardado() {
        return guardado;
    }

    public void setGuardado(boolean guardado) {
        this.guardado = guardado;
    }

    public int getContador() {
        return contador;
    }

    public boolean isHasPrevius() {
        return hasPrevius;
    }

    public void setHasPrevius(boolean hasPrevius) {
        this.hasPrevius = hasPrevius;
    }

    public int getSizeRamdom() {
        return traza.getListaTif().size();
    }

    public void setSizeRamdom(int sizeRamdom) {
        this.sizeRamdom = sizeRamdom;
    }
    /**
     * Creates new form Ventana_1
     *
     * @return
     */
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JInternalFrame internal;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel pagina;
    private javax.swing.JPanel panelButtCheck;
    private javax.swing.JLabel rutaJlabel;
    private javax.swing.JScrollPane scrollChecks;
    private javax.swing.JScrollPane scrollimage;
    private javax.swing.JButton siguiente;
    private javax.swing.JSlider slider;
    private javax.swing.JTable tablaCheck;
    private javax.swing.JButton terminar;
    // End of variables declaration//GEN-END:variables

    private String filtroImagen(boolean ispdf, Imagen siguientes) {
        String ret;
        if (ispdf) {
            worker = new ImagenesWorker(siguientes.getRuta_archivo(), siguientes.getParent(), siguientes.getPagina());
            worker.execute();
            ret = worker.doInBackground();
            siguientes.setRutaTemp(ret);
            int page =siguientes.getPagina()+1;
            pagina.setText("Pagina: " + page);
        } else {
            ret = siguientes.getRuta_archivo();
            pagina.setVisible(false);
        }
        return ret;
    }
}
