/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelesABM;

import Entidades.*;
import Helpers.Version;
import ReporteLote.Reporte;
import Ventana.ImagenesWorker;

import Ventana.VisualizarImagen;
import java.beans.PropertyVetoException;
import java.util.ListIterator;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import necesitoUnMilagro.GetRutaDeImagen;
import necesitoUnMilagro.Guardar;
import necesitoUnMilagro.NumeroRechazo;
import necesitoUnMilagro.SetChecksBox;

/**
 *
 * @author MUTNPROD003
 */
public class Ventana extends javax.swing.JFrame {

 private int sizeRamdom;
    private DefaultTableModel model;
    private TrazaDao traza;
    private ListIterator iterator;
    private boolean hasNext;
    private boolean hasPrevius;
    private int contador = 1;
    private int zoom;
    private ImagenesWorker worker;
    private boolean pdf;

    public Ventana(TrazaDao traza) {
        initComponents();
        setTitle(Version.VERSION);
        tablaCheck.requestFocus();
        this.traza = traza;
        String rutaImagen = "Logos\\nuevo logo sin letras UTN.png";
        ImageIcon im = new ImageIcon(rutaImagen);
        setIconImage(im.getImage());
        setExtendedState(6);
        this.iterator = traza.getListaTif().listIterator();
        terminar.setEnabled(false);
        this.pdf = (traza.getExtension().equals(".pdf")) ? true : false;
        TablaCheckBox tablaCheckBox = new TablaCheckBox(model, tablaCheck, traza);
        internal(pdf);
    }

private void internal(boolean ispdf) {
        try {
            internal.setMaximum(true);
            Imagen siguientes = nextImagen();//trae el ramdom
            anterior.setEnabled(false);
            int id = siguientes.getId();
            String rutaDb = siguientes.getRutaDb();//ruta de archivo
            internal.setTitle("Imagen " + contador + "/" + getSizeRamdom());
            rutaJlabel.setText(rutaDb);
            internal.setVisible(true);
            String verImagen = filtroImagen(ispdf, siguientes);
            VisualizarImagen visualizarImagen = new VisualizarImagen(verImagen, scrollimage, slider, getZoom());
            new SetChecksBox(tablaCheck).set(id);
            contador++;
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ListIterator getIterator() {
        return iterator;
    }

    private Imagen nextImagen() {
        Imagen tif = null;
        try {
            ListIterator it = getIterator();
            tif = (Imagen) it.next();
            hasNext = (!it.hasNext()) ? false : true;
        } catch (NoSuchElementException e) {
            System.out.println(e.getMessage());
        }
        return tif;
    }

    private Imagen previus() {
        Imagen tif = null;
        try {
            ListIterator it = getIterator();
            tif = (Imagen) it.previous();
            hasPrevius = (!it.hasPrevious()) ? false : true;
        } catch (NoSuchElementException e) {
            System.out.println(e.getMessage());
        }
        return tif;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        siguiente = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        terminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        internal = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        scrollimage = new javax.swing.JScrollPane();
        slider = new javax.swing.JSlider();
        rutaJlabel = new javax.swing.JLabel();
        pagina = new javax.swing.JLabel();
        panelButtCheck = new javax.swing.JPanel();
        scrollChecks = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCheck = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 252, 238));

        jPanel1.setBackground(new java.awt.Color(230, 252, 238));

        siguiente.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        anterior.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        terminar.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        terminar.setText("Terminar");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });

        internal.setBackground(new java.awt.Color(230, 252, 238));
        internal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        internal.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        internal.setIconifiable(true);
        internal.setMaximizable(true);
        internal.setResizable(true);
        internal.setTitle("Qualitys_control de imágenes");
        internal.setNextFocusableComponent(tablaCheck);
        internal.setVisible(true);

        slider.setMajorTickSpacing(10);
        slider.setValue(20);

        rutaJlabel.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        rutaJlabel.setText("RUTA");

        pagina.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        pagina.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pagina.setText("Pagina: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollimage)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rutaJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutaJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollimage, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );

        scrollChecks.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jScrollPane4.setBorder(null);

        tablaCheck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Nombre", "?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaCheck.setNextFocusableComponent(siguiente);
        jScrollPane4.setViewportView(tablaCheck);

        scrollChecks.setViewportView(jScrollPane4);

        javax.swing.GroupLayout panelButtCheckLayout = new javax.swing.GroupLayout(panelButtCheck);
        panelButtCheck.setLayout(panelButtCheckLayout);
        panelButtCheckLayout.setHorizontalGroup(
            panelButtCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollChecks, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        panelButtCheckLayout.setVerticalGroup(
            panelButtCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollChecks, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout internalLayout = new javax.swing.GroupLayout(internal.getContentPane());
        internal.getContentPane().setLayout(internalLayout);
        internalLayout.setHorizontalGroup(
            internalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelButtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        internalLayout.setVerticalGroup(
            internalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internalLayout.createSequentialGroup()
                .addGroup(internalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelButtCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        internal.setBounds(10, 10, 830, 480);
        jDesktopPane1.add(internal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setViewportView(jDesktopPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(67, 67, 67)
                .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed
        Guardar save = new Guardar(traza, rutaJlabel.getText().toString(), tablaCheck, pagina, pdf);

        final int id = traza.getId();
        NumeroRechazo numeroRechazo = new NumeroRechazo(id);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Reporte(id).setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_terminarActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        Guardar save = new Guardar(traza, rutaJlabel.getText().toString(), tablaCheck, pagina, pdf);
        Imagen tif = nextImagen();
        String ruta_temp;
        try {
            setZoom(slider.getValue());
            anterior.setEnabled(true);
            internal.setTitle("Imagen  " + contador + "/" + getSizeRamdom());
            rutaJlabel.setText(tif.getRutaDb());
            int page = tif.getPagina() + 1;
            pagina.setText("Pagina: " + page);
            new SetChecksBox(tablaCheck).set(tif.getId());
            GetRutaDeImagen rutaDeImagen = new GetRutaDeImagen(tif, pdf, pagina);
            ruta_temp = rutaDeImagen.getSiguienteRuta();
            VisualizarImagen visualizarImagen = new VisualizarImagen(ruta_temp, scrollimage, slider, getZoom());
            if (!isHasNext()) {
                siguiente.setEnabled(false);
                terminar.setEnabled(true);
            }
            internal.setVisible(true);
            contador++;
        } catch (Exception ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        String visualizacion = "";
        Imagen pr = previus();
        Guardar save = new Guardar(traza, rutaJlabel.getText().toString(), tablaCheck, pagina, pdf);
        int der = contador - 1;
        setContador(der);
        siguiente.setEnabled(true);
        internal.setTitle("Imagen " + getContador() + "/" + getSizeRamdom());
        String rutaPdf = pr.getRutaDb();
        int page = pr.getPagina() + 1;
        rutaJlabel.setText(rutaPdf);
        pagina.setText("Pagina: " + page);
        int id = pr.getId();
        new SetChecksBox(tablaCheck).set(id);

        visualizacion = new GetRutaDeImagen(pr, pdf, pagina).getAnteriorRuta();
        VisualizarImagen visualizarImagen = new VisualizarImagen(visualizacion.replace("\\", "/"), scrollimage, slider, getZoom());
        if (!hasPrevius) {
            anterior.setEnabled(false);
        }
    }//GEN-LAST:event_anteriorActionPerformed

    public int getZoom() {
        return slider.getValue();
    }

    public void setZoom(int zoom) {
        this.zoom = zoom;
    }

    public boolean isHasNext() {
        return hasNext;
    }

    public void setContador(int contador) {
        this.contador = contador;
    }



    public int getContador() {
        return contador;
    }

    public boolean isHasPrevius() {
        return hasPrevius;
    }

    public void setHasPrevius(boolean hasPrevius) {
        this.hasPrevius = hasPrevius;
    }

    public int getSizeRamdom() {
        return traza.getListaTif().size();
    }

    public void setSizeRamdom(int sizeRamdom) {
        this.sizeRamdom = sizeRamdom;
    }
    /**
     * Creates new form Ventana
     *
     * @return
     */
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JInternalFrame internal;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel pagina;
    private javax.swing.JPanel panelButtCheck;
    private javax.swing.JLabel rutaJlabel;
    private javax.swing.JScrollPane scrollChecks;
    private javax.swing.JScrollPane scrollimage;
    private javax.swing.JButton siguiente;
    private javax.swing.JSlider slider;
    private javax.swing.JTable tablaCheck;
    private javax.swing.JButton terminar;
    // End of variables declaration//GEN-END:variables

    private String filtroImagen(boolean ispdf, Imagen siguientes) {
        String ret;
        if (ispdf) {
            worker = new ImagenesWorker(siguientes.getRuta_archivo(), siguientes.getParent(), siguientes.getPagina());
            worker.execute();
            ret = worker.doInBackground();
            siguientes.setRutaTemp(ret);
            int page =siguientes.getPagina()+1;
            pagina.setText("Pagina: " + page);
        } else {
            ret = siguientes.getRuta_archivo();
            pagina.setVisible(false);
        }
        return ret;
    }
}
