/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Rangos.Paq.Desactivar;
import java.awt.Rectangle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import writeproperties.Conexion;

/**
 *
 * @author MUTNPROD003
 */
public class ControlesABM extends javax.swing.JFrame {
    private static final String INSTRUCCIONES = "Para INSERTAR un nuevo elemento, oprima 'AGREGAR CONTROL',"
            + "\n inserte los datos en la fila vacia y oprima GUARDAR.\n"
            + "Para EDITAR un contenido, oprima 'EDITAR CONTROL',\n "
            + "modifique los datos y oprima GUARDAR.\n"
            + "Para desactivar un control, posarse sobre la columna 'id' y oprimir 'DESACTIVAR CONTROL'.";
    private String evento;
    private ControlesDao controles;
    private Conexion conexion = new Conexion();
    private DefaultTableModel modelo;
    private int ide;

    /**
     * Creates new form ControlesABM
     */
    public ControlesABM() {
        initComponents();
        controles = new ControlesDao(tablaContenido, conexion,  ABM);
        principalInternal.setVisible(true);
        modelo = (DefaultTableModel) tablaContenido.getModel();
        salvar.setVisible(false);
        agregar.setVisible(false);
        editar.setVisible(false);
        desactivar.setVisible(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();
        ABM = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        desk = new javax.swing.JDesktopPane();
        principalInternal = new javax.swing.JInternalFrame();
        editar = new javax.swing.JButton();
        desactivar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContenido = new javax.swing.JTable();
        agregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta, Baja y Modificacion de Controles");
        setResizable(false);

        cerrar.setText("cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        ABM.setText("Activar ABM");
        ABM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ABM, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ABM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        principalInternal.setTitle("Para Editar los contenidos presione Activar ABM");
        principalInternal.setVisible(true);

        editar.setText("Editar Control");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        desactivar.setText("Desactivar Control");
        desactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivarActionPerformed(evt);
            }
        });

        salvar.setText("Guardar ");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        tablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "descripcion", "imagen", "Est"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaContenido);
        tablaContenido.getColumnModel().getColumn(0).setResizable(false);
        tablaContenido.getColumnModel().getColumn(1).setResizable(false);
        tablaContenido.getColumnModel().getColumn(2).setResizable(false);
        tablaContenido.getColumnModel().getColumn(3).setResizable(false);
        tablaContenido.getColumnModel().getColumn(4).setResizable(false);

        agregar.setText("Agregar Control");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principalInternalLayout = new javax.swing.GroupLayout(principalInternal.getContentPane());
        principalInternal.getContentPane().setLayout(principalInternalLayout);
        principalInternalLayout.setHorizontalGroup(
            principalInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(principalInternalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalInternalLayout.createSequentialGroup()
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(desactivar)
                        .addGap(25, 25, 25))
                    .addGroup(principalInternalLayout.createSequentialGroup()
                        .addGroup(principalInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(principalInternalLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        principalInternalLayout.setVerticalGroup(
            principalInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalInternalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(editar)
                    .addComponent(desactivar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salvar)
                .addGap(24, 24, 24))
        );

        principalInternal.setBounds(0, 0, 760, 510);
        desk.add(principalInternal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        scroll.setViewportView(desk);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        controles.setEditable(true);
        int idTable = getIde() + 1;
        Object[] ob = new Object[]{idTable};
        modelo.addRow(ob);
        int row = tablaContenido.getRowCount()-1;
        Rectangle rect = tablaContenido.getCellRect(row, 0, true);
        tablaContenido.scrollRectToVisible(rect);
        tablaContenido.clearSelection();
        tablaContenido.setRowSelectionInterval(row, row);
        modelo.fireTableDataChanged();
        salvar.setVisible(true);
        evento = "Agregar";

    }//GEN-LAST:event_agregarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        controles.setEditable(true);
        salvar.setVisible(true);
        evento="Editar";

    }//GEN-LAST:event_editarActionPerformed

    private void desactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivarActionPerformed

        controles.setEditable(true);
        int idjtext = (tablaContenido.getSelectedRow());
        Desactivar desactivar1 = new Desactivar(idjtext, modelo, conexion, "controles", 4);
        tablaContenido.repaint();

    }//GEN-LAST:event_desactivarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        botonGuardar();
    }//GEN-LAST:event_salvarActionPerformed
    private void botonGuardar() {
        switch (evento) {
            case "Agregar":
                tablaContenido.editCellAt(-1, -1);
                controles.getInsertar().insert_newControl(getIde());
                tablaContenido.repaint();
                salvar.setVisible(false);
                break;
            case "Editar":
                tablaContenido.editCellAt(-1, -1);
                int row = tablaContenido.getSelectedRow();
                int idjtext = (row);
                controles.getEditar().controles_SetRow(idjtext);
                tablaContenido.repaint();
                break;
        }
    }
    private void ABMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMActionPerformed
        JOptionPane.showMessageDialog(tablaContenido,INSTRUCCIONES);
        principalInternal.setTitle("Modulo de Edicion");
        agregar.setVisible(true);
        editar.setVisible(true);
        desactivar.setVisible(true);

    }//GEN-LAST:event_ABMActionPerformed

    public int getIde() {
        return controles.getLastId();
    }

    public void setIde(int ide) {
        this.ide = ide;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABM;
    private javax.swing.JButton agregar;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton desactivar;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JButton editar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JInternalFrame principalInternal;
    private javax.swing.JButton salvar;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tablaContenido;
    // End of variables declaration//GEN-END:variables
}
